[2025-04-26T06:21:28.247+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_data_pipeline.submit_traffic_processor_spark_job manual__2025-04-26T06:21:27.768577+00:00 [queued]>
[2025-04-26T06:21:28.259+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_data_pipeline.submit_traffic_processor_spark_job manual__2025-04-26T06:21:27.768577+00:00 [queued]>
[2025-04-26T06:21:28.260+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-26T06:21:28.279+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): submit_traffic_processor_spark_job> on 2025-04-26 06:21:27.768577+00:00
[2025-04-26T06:21:28.285+0000] {standard_task_runner.py:60} INFO - Started process 1144 to run task
[2025-04-26T06:21:28.288+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'traffic_data_pipeline', 'submit_traffic_processor_spark_job', 'manual__2025-04-26T06:21:27.768577+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/traffic_pipeline_dag.py', '--cfg-path', '/tmp/tmpidmizv29']
[2025-04-26T06:21:28.291+0000] {standard_task_runner.py:88} INFO - Job 40: Subtask submit_traffic_processor_spark_job
[2025-04-26T06:21:28.365+0000] {task_command.py:423} INFO - Running <TaskInstance: traffic_data_pipeline.submit_traffic_processor_spark_job manual__2025-04-26T06:21:27.768577+00:00 [running]> on host df84b95b25c0
[2025-04-26T06:21:28.488+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='traffic_data_pipeline' AIRFLOW_CTX_TASK_ID='submit_traffic_processor_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-04-26T06:21:27.768577+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-26T06:21:27.768577+00:00'
[2025-04-26T06:21:28.489+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-26T06:21:28.491+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            echo "--- Checking Line Endings for processor.py ---"\n            cat -e /opt/spark/app/processor.py | head -n 10\n            echo "--- Finished Checking Line Endings ---"\n            echo "Setting PYTHONPATH..."\n            PYTHON_USER_SITE="/home/***/.local/lib/python3.10/site-packages"\n            export PYTHONPATH="${PYTHON_USER_SITE}:${PYTHONPATH:-}"\n            echo "Using PYTHONPATH=$PYTHONPATH"\n            echo "Exporting other environment variables..."\n            export KAFKA_BROKERS_INTERNAL="$KAFKA_BROKERS_INTERNAL" && \\\n            export KAFKA_TOPIC="$KAFKA_TOPIC" && \\\n            export SCHEMA_REGISTRY_URL="$SCHEMA_REGISTRY_URL" && \\\n            export REDIS_HOST="$REDIS_HOST" && \\\n            export CLICKHOUSE_HOST="$CLICKHOUSE_HOST" && \\\n            export CLICKHOUSE_NATIVE_PORT="$CLICKHOUSE_NATIVE_PORT" && \\\n            export MINIO_ENDPOINT="$MINIO_ENDPOINT" && \\\n            export MINIO_ACCESS_KEY="$MINIO_ACCESS_KEY" && \\\n            export MINIO_SECRET_KEY="$MINIO_SECRET_KEY" && \\\n            export MINIO_BUCKET="$MINIO_BUCKET" && \\\n            CHECKPOINT_LOCATION_VAR="s3a://${MINIO_BUCKET:-traffic-data}/checkpoints_***/traffic_processing_pipeline" && \\\n            export CHECKPOINT_LOCATION="$CHECKPOINT_LOCATION_VAR" && \\\n            export PYSPARK_PYTHON=/usr/bin/python3 && \\\n            echo "--- Running Spark Submit ---" && \\\n            spark-submit \\\n            --master local[*] \\\n            --deploy-mode client \\\n            --conf spark.sql.streaming.schemaInference=true \\\n            --conf spark.hadoop.fs.s3a.endpoint="$MINIO_ENDPOINT" \\\n            --conf spark.hadoop.fs.s3a.access.key="$MINIO_ACCESS_KEY" \\\n            --conf spark.hadoop.fs.s3a.secret.key="$MINIO_SECRET_KEY" \\\n            --conf spark.hadoop.fs.s3a.path.style.access=true \\\n            --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem \\\n            --conf spark.sql.avro.schemaRegistryUrl="$SCHEMA_REGISTRY_URL" \\\n            /opt/spark/app/processor.py\n            ']
[2025-04-26T06:21:28.501+0000] {subprocess.py:86} INFO - Output:
[2025-04-26T06:21:28.503+0000] {subprocess.py:93} INFO - --- Checking Line Endings for processor.py ---
[2025-04-26T06:21:28.507+0000] {subprocess.py:93} INFO - import os$
[2025-04-26T06:21:28.508+0000] {subprocess.py:93} INFO - import json$
[2025-04-26T06:21:28.509+0000] {subprocess.py:93} INFO - import math$
[2025-04-26T06:21:28.509+0000] {subprocess.py:93} INFO - from datetime import datetime$
[2025-04-26T06:21:28.510+0000] {subprocess.py:93} INFO - import traceback$
[2025-04-26T06:21:28.511+0000] {subprocess.py:93} INFO - $
[2025-04-26T06:21:28.512+0000] {subprocess.py:93} INFO - # Import thM-FM-0 viM-aM-;M-^Gn cM-aM-:M-'n thiM-aM-:M-?t cho Pandas UDF$
[2025-04-26T06:21:28.513+0000] {subprocess.py:93} INFO - import pandas as pd$
[2025-04-26T06:21:28.513+0000] {subprocess.py:93} INFO - from pyspark.sql import SparkSession$
[2025-04-26T06:21:28.514+0000] {subprocess.py:93} INFO - from pyspark.sql.functions import col, window, avg, count, udf, lit, expr, pandas_udf, PandasUDFType, year, month, dayofmonth, hour$
[2025-04-26T06:21:28.515+0000] {subprocess.py:93} INFO - --- Finished Checking Line Endings ---
[2025-04-26T06:21:28.516+0000] {subprocess.py:93} INFO - Setting PYTHONPATH...
[2025-04-26T06:21:28.516+0000] {subprocess.py:93} INFO - Using PYTHONPATH=/home/***/.local/lib/python3.10/site-packages:
[2025-04-26T06:21:28.517+0000] {subprocess.py:93} INFO - Exporting other environment variables...
[2025-04-26T06:21:28.518+0000] {subprocess.py:93} INFO - --- Running Spark Submit ---
[2025-04-26T06:21:28.518+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-26T06:21:30.579+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-26T06:21:30.580+0000] {subprocess.py:93} INFO -   File "/opt/spark/app/processor.py", line 8, in <module>
[2025-04-26T06:21:30.582+0000] {subprocess.py:93} INFO -     import pandas as pd
[2025-04-26T06:21:30.582+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/pandas/__init__.py", line 16, in <module>
[2025-04-26T06:21:30.583+0000] {subprocess.py:93} INFO -     raise ImportError(
[2025-04-26T06:21:30.583+0000] {subprocess.py:93} INFO - ImportError: Unable to import required dependencies:
[2025-04-26T06:21:30.583+0000] {subprocess.py:93} INFO - numpy:
[2025-04-26T06:21:30.584+0000] {subprocess.py:93} INFO - 
[2025-04-26T06:21:30.585+0000] {subprocess.py:93} INFO - IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[2025-04-26T06:21:30.585+0000] {subprocess.py:93} INFO - 
[2025-04-26T06:21:30.586+0000] {subprocess.py:93} INFO - Importing the numpy C-extensions failed. This error can happen for
[2025-04-26T06:21:30.586+0000] {subprocess.py:93} INFO - many reasons, often due to issues with your setup or how NumPy was
[2025-04-26T06:21:30.586+0000] {subprocess.py:93} INFO - installed.
[2025-04-26T06:21:30.587+0000] {subprocess.py:93} INFO - 
[2025-04-26T06:21:30.587+0000] {subprocess.py:93} INFO - We have compiled some common reasons and troubleshooting tips at:
[2025-04-26T06:21:30.587+0000] {subprocess.py:93} INFO - 
[2025-04-26T06:21:30.590+0000] {subprocess.py:93} INFO -     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[2025-04-26T06:21:30.591+0000] {subprocess.py:93} INFO - 
[2025-04-26T06:21:30.592+0000] {subprocess.py:93} INFO - Please note and check the following:
[2025-04-26T06:21:30.592+0000] {subprocess.py:93} INFO - 
[2025-04-26T06:21:30.593+0000] {subprocess.py:93} INFO -   * The Python version is: Python3.11 from "/usr/bin/python3"
[2025-04-26T06:21:30.594+0000] {subprocess.py:93} INFO -   * The NumPy version is: "1.24.4"
[2025-04-26T06:21:30.595+0000] {subprocess.py:93} INFO - 
[2025-04-26T06:21:30.595+0000] {subprocess.py:93} INFO - and make sure that they are the versions you expect.
[2025-04-26T06:21:30.596+0000] {subprocess.py:93} INFO - Please carefully study the documentation linked above for further help.
[2025-04-26T06:21:30.597+0000] {subprocess.py:93} INFO - 
[2025-04-26T06:21:30.598+0000] {subprocess.py:93} INFO - Original error was: No module named 'numpy.core._multiarray_umath'
[2025-04-26T06:21:30.598+0000] {subprocess.py:93} INFO - 
[2025-04-26T06:21:30.600+0000] {subprocess.py:93} INFO - 25/04/26 06:21:30 INFO ShutdownHookManager: Shutdown hook called
[2025-04-26T06:21:30.605+0000] {subprocess.py:93} INFO - 25/04/26 06:21:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-e614dd19-6caa-48e9-b4b7-39ba4678ea9a
[2025-04-26T06:21:30.641+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-26T06:21:30.657+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-26T06:21:30.661+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=traffic_data_pipeline, task_id=submit_traffic_processor_spark_job, execution_date=20250426T062127, start_date=20250426T062128, end_date=20250426T062130
[2025-04-26T06:21:30.677+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 40 for task submit_traffic_processor_spark_job (Bash command failed. The command returned a non-zero exit code 1.; 1144)
[2025-04-26T06:21:30.715+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-26T06:21:30.757+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
