[2025-04-28T10:52:39.437+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_data_pipeline.submit_traffic_processor_spark_job manual__2025-04-28T10:46:29.602071+00:00 [queued]>
[2025-04-28T10:52:39.447+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_data_pipeline.submit_traffic_processor_spark_job manual__2025-04-28T10:46:29.602071+00:00 [queued]>
[2025-04-28T10:52:39.447+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 1
[2025-04-28T10:52:39.464+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): submit_traffic_processor_spark_job> on 2025-04-28 10:46:29.602071+00:00
[2025-04-28T10:52:39.471+0000] {standard_task_runner.py:60} INFO - Started process 215 to run task
[2025-04-28T10:52:39.477+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'traffic_data_pipeline', 'submit_traffic_processor_spark_job', 'manual__2025-04-28T10:46:29.602071+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/traffic_pipeline_dag.py', '--cfg-path', '/tmp/tmpqhyopv2k']
[2025-04-28T10:52:39.480+0000] {standard_task_runner.py:88} INFO - Job 83: Subtask submit_traffic_processor_spark_job
[2025-04-28T10:52:39.602+0000] {task_command.py:423} INFO - Running <TaskInstance: traffic_data_pipeline.submit_traffic_processor_spark_job manual__2025-04-28T10:46:29.602071+00:00 [running]> on host 02173e944d7b
[2025-04-28T10:52:39.714+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='traffic_data_pipeline' AIRFLOW_CTX_TASK_ID='submit_traffic_processor_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T10:46:29.602071+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T10:46:29.602071+00:00'
[2025-04-28T10:52:39.715+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-28T10:52:39.717+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            echo "--- Checking Line Endings for processor.py ---"\n            cat -e /opt/spark/app/processor.py | head -n 10\n            echo "--- Finished Checking Line Endings ---"\n            echo "Setting PYTHONPATH..."\n            PYTHON_USER_SITE="/home/***/.local/lib/python3.10/site-packages"\n            export PYTHONPATH="${PYTHON_USER_SITE}:${PYTHONPATH:-}"\n            echo "Using PYTHONPATH=$PYTHONPATH"\n            echo "Exporting other environment variables..."\n            export KAFKA_BROKERS_INTERNAL="$KAFKA_BROKERS_INTERNAL" && \\\n            export KAFKA_TOPIC="$KAFKA_TOPIC" && \\\n            export SCHEMA_REGISTRY_URL="$SCHEMA_REGISTRY_URL" && \\\n            export REDIS_HOST="$REDIS_HOST" && \\\n            export CLICKHOUSE_HOST="$CLICKHOUSE_HOST" && \\\n            export CLICKHOUSE_NATIVE_PORT="$CLICKHOUSE_NATIVE_PORT" && \\\n            export MINIO_ENDPOINT="$MINIO_ENDPOINT" && \\\n            export MINIO_ACCESS_KEY="$MINIO_ACCESS_KEY" && \\\n            export MINIO_SECRET_KEY="$MINIO_SECRET_KEY" && \\\n            export MINIO_BUCKET="$MINIO_BUCKET" && \\\n            CHECKPOINT_LOCATION_VAR="s3a://${MINIO_BUCKET:-traffic-data}/checkpoints_***/traffic_processing_pipeline" && \\\n            export CHECKPOINT_LOCATION="$CHECKPOINT_LOCATION_VAR" && \\\n            export PYSPARK_PYTHON=/usr/local/bin/python3.10 && \\\n            echo "--- Running Spark Submit ---" && \\\n            spark-submit \\\n            --master local[*] \\\n            --deploy-mode client \\\n            --conf spark.sql.streaming.schemaInference=true \\\n            --conf spark.hadoop.fs.s3a.endpoint="$MINIO_ENDPOINT" \\\n            --conf spark.hadoop.fs.s3a.access.key="$MINIO_ACCESS_KEY" \\\n            --conf spark.hadoop.fs.s3a.secret.key="$MINIO_SECRET_KEY" \\\n            --conf spark.hadoop.fs.s3a.path.style.access=true \\\n            --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem \\\n            --conf spark.sql.avro.schemaRegistryUrl="$SCHEMA_REGISTRY_URL" \\\n            /opt/spark/app/processor.py\n            ']
[2025-04-28T10:52:39.737+0000] {subprocess.py:86} INFO - Output:
[2025-04-28T10:52:39.738+0000] {subprocess.py:93} INFO - --- Checking Line Endings for processor.py ---
[2025-04-28T10:52:39.745+0000] {subprocess.py:93} INFO - import os$
[2025-04-28T10:52:39.746+0000] {subprocess.py:93} INFO - import json$
[2025-04-28T10:52:39.747+0000] {subprocess.py:93} INFO - import math$
[2025-04-28T10:52:39.748+0000] {subprocess.py:93} INFO - from datetime import datetime$
[2025-04-28T10:52:39.748+0000] {subprocess.py:93} INFO - import traceback$
[2025-04-28T10:52:39.749+0000] {subprocess.py:93} INFO - from typing import Optional$
[2025-04-28T10:52:39.749+0000] {subprocess.py:93} INFO - $
[2025-04-28T10:52:39.750+0000] {subprocess.py:93} INFO - # Import thM-FM-0 viM-aM-;M-^Gn cM-aM-:M-'n thiM-aM-:M-?t cho Pandas UDF$
[2025-04-28T10:52:39.751+0000] {subprocess.py:93} INFO - import pandas as pd$
[2025-04-28T10:52:39.751+0000] {subprocess.py:93} INFO - from pyspark.sql import SparkSession$
[2025-04-28T10:52:39.752+0000] {subprocess.py:93} INFO - --- Finished Checking Line Endings ---
[2025-04-28T10:52:39.752+0000] {subprocess.py:93} INFO - Setting PYTHONPATH...
[2025-04-28T10:52:39.753+0000] {subprocess.py:93} INFO - Using PYTHONPATH=/home/***/.local/lib/python3.10/site-packages:
[2025-04-28T10:52:39.754+0000] {subprocess.py:93} INFO - Exporting other environment variables...
[2025-04-28T10:52:39.754+0000] {subprocess.py:93} INFO - --- Running Spark Submit ---
[2025-04-28T10:52:39.759+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-28T10:52:45.339+0000] {subprocess.py:93} INFO - --- PySpark Script Dependencies Imported ---
[2025-04-28T10:52:45.340+0000] {subprocess.py:93} INFO - --- Starting Spark Streaming Traffic Processor ---
[2025-04-28T10:52:45.340+0000] {subprocess.py:93} INFO - Reading from Kafka: kafk-1:9092,kafk-2:9092,kafk-3:9092 / Topic: raw_traffic_data
[2025-04-28T10:52:45.341+0000] {subprocess.py:93} INFO - Avro Schema File: /opt/spark/schemas/raw_traffic_event.avsc
[2025-04-28T10:52:45.342+0000] {subprocess.py:93} INFO - Writing state to Redis: redis:6379
[2025-04-28T10:52:45.342+0000] {subprocess.py:93} INFO - Writing history to ClickHouse: clickhouse-server:8123 (DB: traffic_db)
[2025-04-28T10:52:45.343+0000] {subprocess.py:93} INFO - Writing Parquet to MinIO Bucket: s3a://traffic-data/
[2025-04-28T10:52:45.343+0000] {subprocess.py:93} INFO - Checkpoint Location Base: s3a://traffic-data/checkpoints_***/traffic_processing_pipeline
[2025-04-28T10:52:45.488+0000] {subprocess.py:93} INFO - 25/04/28 10:52:45 INFO SparkContext: Running Spark version 3.3.4
[2025-04-28T10:52:45.640+0000] {subprocess.py:93} INFO - 25/04/28 10:52:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-28T10:52:45.895+0000] {subprocess.py:93} INFO - 25/04/28 10:52:45 INFO ResourceUtils: ==============================================================
[2025-04-28T10:52:45.896+0000] {subprocess.py:93} INFO - 25/04/28 10:52:45 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-04-28T10:52:45.898+0000] {subprocess.py:93} INFO - 25/04/28 10:52:45 INFO ResourceUtils: ==============================================================
[2025-04-28T10:52:45.901+0000] {subprocess.py:93} INFO - 25/04/28 10:52:45 INFO SparkContext: Submitted application: TrafficProcessorDE
[2025-04-28T10:52:45.967+0000] {subprocess.py:93} INFO - 25/04/28 10:52:45 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-04-28T10:52:45.983+0000] {subprocess.py:93} INFO - 25/04/28 10:52:45 INFO ResourceProfile: Limiting resource is cpu
[2025-04-28T10:52:45.986+0000] {subprocess.py:93} INFO - 25/04/28 10:52:45 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-04-28T10:52:46.092+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO SecurityManager: Changing view acls to: ***
[2025-04-28T10:52:46.094+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO SecurityManager: Changing modify acls to: ***
[2025-04-28T10:52:46.094+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO SecurityManager: Changing view acls groups to:
[2025-04-28T10:52:46.095+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO SecurityManager: Changing modify acls groups to:
[2025-04-28T10:52:46.096+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2025-04-28T10:52:46.486+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO Utils: Successfully started service 'sparkDriver' on port 46033.
[2025-04-28T10:52:46.574+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO SparkEnv: Registering MapOutputTracker
[2025-04-28T10:52:46.642+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO SparkEnv: Registering BlockManagerMaster
[2025-04-28T10:52:46.679+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-04-28T10:52:46.682+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-04-28T10:52:46.693+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-04-28T10:52:46.733+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-83a9d922-059d-4a86-aab9-e3f02bab66f0
[2025-04-28T10:52:46.767+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-04-28T10:52:46.788+0000] {subprocess.py:93} INFO - 25/04/28 10:52:46 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-04-28T10:52:47.193+0000] {subprocess.py:93} INFO - 25/04/28 10:52:47 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-04-28T10:52:47.451+0000] {subprocess.py:93} INFO - 25/04/28 10:52:47 INFO Executor: Starting executor ID driver on host 02173e944d7b
[2025-04-28T10:52:47.462+0000] {subprocess.py:93} INFO - 25/04/28 10:52:47 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-04-28T10:52:47.504+0000] {subprocess.py:93} INFO - 25/04/28 10:52:47 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34801.
[2025-04-28T10:52:47.507+0000] {subprocess.py:93} INFO - 25/04/28 10:52:47 INFO NettyBlockTransferService: Server created on 02173e944d7b:34801
[2025-04-28T10:52:47.514+0000] {subprocess.py:93} INFO - 25/04/28 10:52:47 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-04-28T10:52:47.529+0000] {subprocess.py:93} INFO - 25/04/28 10:52:47 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 02173e944d7b, 34801, None)
[2025-04-28T10:52:47.544+0000] {subprocess.py:93} INFO - 25/04/28 10:52:47 INFO BlockManagerMasterEndpoint: Registering block manager 02173e944d7b:34801 with 434.4 MiB RAM, BlockManagerId(driver, 02173e944d7b, 34801, None)
[2025-04-28T10:52:47.545+0000] {subprocess.py:93} INFO - 25/04/28 10:52:47 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 02173e944d7b, 34801, None)
[2025-04-28T10:52:47.547+0000] {subprocess.py:93} INFO - 25/04/28 10:52:47 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 02173e944d7b, 34801, None)
[2025-04-28T10:52:48.636+0000] {subprocess.py:93} INFO - Spark Session created. Spark version: 3.3.4
[2025-04-28T10:52:48.637+0000] {subprocess.py:93} INFO - Using PySpark version: 3.3.4
[2025-04-28T10:52:48.637+0000] {subprocess.py:93} INFO - Broadcasting segments data...
[2025-04-28T10:52:48.927+0000] {subprocess.py:93} INFO - Segments data broadcasted successfully.
[2025-04-28T10:52:49.383+0000] {subprocess.py:93} INFO - /opt/spark/python/lib/pyspark.zip/pyspark/sql/pandas/functions.py:394: UserWarning: In Python 3.6+ and Spark 3.0+, it is preferred to specify type hints for pandas UDF instead of specifying pandas UDF type which will be deprecated in the future releases. See SPARK-28264 for more details.
[2025-04-28T10:52:49.384+0000] {subprocess.py:93} INFO - Pandas UDF for map matching defined.
[2025-04-28T10:52:49.385+0000] {subprocess.py:93} INFO - Setting up Kafka stream reader...
[2025-04-28T10:52:49.385+0000] {subprocess.py:93} INFO - Kafka Read Options: {'kafka.bootstrap.servers': 'kafk-1:9092,kafk-2:9092,kafk-3:9092', 'subscribe': 'raw_traffic_data', 'startingOffsets': 'earliest', 'failOnDataLoss': 'false'}
[2025-04-28T10:52:54.178+0000] {subprocess.py:93} INFO - Kafka stream reader loaded.
[2025-04-28T10:52:54.179+0000] {subprocess.py:93} INFO - Reading Avro schema from file: /opt/spark/schemas/raw_traffic_event.avsc
[2025-04-28T10:52:54.182+0000] {subprocess.py:93} INFO - Successfully read Avro schema string from file.
[2025-04-28T10:52:54.182+0000] {subprocess.py:93} INFO - Setting up Avro deserialization...
[2025-04-28T10:52:54.639+0000] {subprocess.py:93} INFO - Avro deserialization step defined.
[2025-04-28T10:52:54.640+0000] {subprocess.py:93} INFO - Defining data processing steps...
[2025-04-28T10:52:55.287+0000] {subprocess.py:93} INFO - Data processing steps defined.
[2025-04-28T10:52:55.288+0000] {subprocess.py:93} INFO - Using checkpoint location: s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2
[2025-04-28T10:52:55.289+0000] {subprocess.py:93} INFO - Starting streaming query...
[2025-04-28T10:52:55.656+0000] {subprocess.py:93} INFO - 25/04/28 10:52:55 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-04-28T10:52:57.427+0000] {subprocess.py:93} INFO - 25/04/28 10:52:57 WARN ResolveWriteToStream: spark.sql.adaptive.enabled is not supported in streaming DataFrames/Datasets and will be disabled.
[2025-04-28T10:52:57.888+0000] {subprocess.py:93} INFO - Streaming query 'traffic_processing_pipeline_debug2' started successfully.
[2025-04-28T10:53:05.409+0000] {subprocess.py:93} INFO - 25/04/28 10:53:05 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:05.413+0000] {subprocess.py:93} INFO - 25/04/28 10:53:05 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:05.414+0000] {subprocess.py:93} INFO - 25/04/28 10:53:05 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.709+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.710+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.713+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.716+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.717+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.721+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.722+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.723+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.724+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.725+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.726+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.727+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.727+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.728+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.729+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.730+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.731+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.731+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.733+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.734+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.735+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.735+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.737+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.739+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.742+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.745+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.747+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.751+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.753+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.756+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.758+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.761+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.763+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.764+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.764+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.765+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.766+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.767+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.768+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.768+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.769+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.770+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.770+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.771+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.772+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.774+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.774+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.775+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.776+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.778+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.778+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.779+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.780+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.780+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.781+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.782+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.783+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.783+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.784+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.784+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.785+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.785+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.786+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.786+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.787+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.788+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.788+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.789+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.790+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.790+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.791+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.792+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.794+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.798+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.798+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.799+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.800+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.801+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.801+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.802+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.803+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.804+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.804+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.805+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.806+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.806+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.807+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.808+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.810+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.811+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.812+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.814+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.815+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.817+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.818+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.819+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.820+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.820+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.821+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.822+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.822+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.823+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.824+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.824+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.825+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.825+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.826+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.827+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.828+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.828+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.829+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.833+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.836+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.837+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.838+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.838+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.839+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.840+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.841+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.841+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.842+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.843+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.844+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.844+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.845+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.846+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.847+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.847+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.848+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.849+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.858+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.859+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.862+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.863+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.868+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.872+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.877+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.879+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.880+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.881+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.882+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.882+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.883+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.884+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.885+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.886+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.887+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.888+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.889+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.889+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.890+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.891+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.891+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.892+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.894+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.895+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.896+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.898+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.901+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.901+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.902+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.903+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.905+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.906+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.907+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.907+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.908+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.909+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.909+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.910+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.910+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.911+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.911+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.912+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.913+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.914+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.915+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.917+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.918+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.920+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.921+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.922+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.923+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.924+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.925+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.925+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.926+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.927+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.927+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.928+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.929+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.930+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.930+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.931+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.932+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.933+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.935+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.936+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.939+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.942+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.943+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.944+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.945+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.946+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.946+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.947+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.948+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.949+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.949+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.952+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.955+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.958+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.959+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.960+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.963+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.965+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.966+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.967+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.967+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.968+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.969+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.969+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.970+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.971+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.971+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.972+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.973+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.974+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.974+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.975+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.977+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.978+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.978+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.980+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.981+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.982+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.983+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.983+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.984+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.985+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.985+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.986+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.987+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.988+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.988+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.989+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.990+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.990+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.998+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:07.999+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:08.000+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:08.004+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:08.006+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:08.009+0000] {subprocess.py:93} INFO - 25/04/28 10:53:07 WARN KafkaDataConsumer: KafkaDataConsumer is not running in UninterruptibleThread. It may hang when KafkaDataConsumer's methods are interrupted because of KAFKA-1894
[2025-04-28T10:53:12.216+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.244+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.288+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.323+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.363+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.416+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.477+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.539+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.556+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.584+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.650+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.712+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.738+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:12.812+0000] {subprocess.py:93} INFO - 25/04/28 10:53:12 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:13.072+0000] {subprocess.py:93} INFO - 25/04/28 10:53:13 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:13.100+0000] {subprocess.py:93} INFO - 25/04/28 10:53:13 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:16.184+0000] {subprocess.py:93} INFO - 25/04/28 10:53:16 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:16.343+0000] {subprocess.py:93} INFO - 25/04/28 10:53:16 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:16.427+0000] {subprocess.py:93} INFO - 25/04/28 10:53:16 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:16.707+0000] {subprocess.py:93} INFO - 25/04/28 10:53:16 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:16.816+0000] {subprocess.py:93} INFO - 25/04/28 10:53:16 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:17.112+0000] {subprocess.py:93} INFO - 25/04/28 10:53:17 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:18.072+0000] {subprocess.py:93} INFO - 25/04/28 10:53:18 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:18.302+0000] {subprocess.py:93} INFO - 25/04/28 10:53:18 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:18.426+0000] {subprocess.py:93} INFO - 25/04/28 10:53:18 WARN CheckpointFileManager: Failed to rename temp file s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/17/.9.delta.536b9fb0-d8c6-49b5-a897-d43c55853d19.TID20.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/17/9.delta because file exists
[2025-04-28T10:53:18.494+0000] {subprocess.py:93} INFO - org.apache.hadoop.fs.FileAlreadyExistsException: Failed to rename s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/17/.9.delta.536b9fb0-d8c6-49b5-a897-d43c55853d19.TID20.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/17/9.delta; destination file exists
[2025-04-28T10:53:18.497+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.initiateRename(S3AFileSystem.java:1920)
[2025-04-28T10:53:18.498+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerRename(S3AFileSystem.java:1988)
[2025-04-28T10:53:18.502+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$rename$7(S3AFileSystem.java:1846)
[2025-04-28T10:53:18.509+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-04-28T10:53:18.511+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDuration(IOStatisticsBinding.java:444)
[2025-04-28T10:53:18.515+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2337)
[2025-04-28T10:53:18.517+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.rename(S3AFileSystem.java:1844)
[2025-04-28T10:53:18.519+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.rename(FileSystem.java:1624)
[2025-04-28T10:53:18.522+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.DelegateToFileSystem.renameInternal(DelegateToFileSystem.java:206)
[2025-04-28T10:53:18.525+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.renameInternal(AbstractFileSystem.java:790)
[2025-04-28T10:53:18.528+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[2025-04-28T10:53:18.531+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileContext.rename(FileContext.java:1036)
[2025-04-28T10:53:18.541+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileContextBasedCheckpointFileManager.renameTempFile(CheckpointFileManager.scala:346)
[2025-04-28T10:53:18.542+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.CheckpointFileManager$RenameBasedFSDataOutputStream.close(CheckpointFileManager.scala:154)
[2025-04-28T10:53:18.544+0000] {subprocess.py:93} INFO - 	at net.jpountz.lz4.LZ4BlockOutputStream.close(LZ4BlockOutputStream.java:198)
[2025-04-28T10:53:18.548+0000] {subprocess.py:93} INFO - 	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[2025-04-28T10:53:18.549+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.finalizeDeltaFile(HDFSBackedStateStoreProvider.scala:450)
[2025-04-28T10:53:18.554+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$commitUpdates(HDFSBackedStateStoreProvider.scala:320)
[2025-04-28T10:53:18.558+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider$HDFSBackedStateStore.commit(HDFSBackedStateStoreProvider.scala:141)
[2025-04-28T10:53:18.563+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.StreamingAggregationStateManagerBaseImpl.commit(StreamingAggregationStateManager.scala:89)
[2025-04-28T10:53:18.565+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.$anonfun$close$3(statefulOperators.scala:481)
[2025-04-28T10:53:18.566+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-28T10:53:18.570+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:642)
[2025-04-28T10:53:18.571+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs(statefulOperators.scala:142)
[2025-04-28T10:53:18.573+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs$(statefulOperators.scala:142)
[2025-04-28T10:53:18.576+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec.timeTakenMs(statefulOperators.scala:352)
[2025-04-28T10:53:18.577+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.close(statefulOperators.scala:481)
[2025-04-28T10:53:18.578+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.closeIfNeeded(NextIterator.scala:66)
[2025-04-28T10:53:18.579+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:75)
[2025-04-28T10:53:18.583+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.hashAgg_doAggregateWithKeys_0$(Unknown Source)
[2025-04-28T10:53:18.586+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.processNext(Unknown Source)
[2025-04-28T10:53:18.591+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-04-28T10:53:18.595+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
[2025-04-28T10:53:18.596+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:18.599+0000] {subprocess.py:93} INFO - 	at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)
[2025-04-28T10:53:18.600+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:18.604+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:18.605+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)
[2025-04-28T10:53:18.608+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)
[2025-04-28T10:53:18.611+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:18.613+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2025-04-28T10:53:18.617+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2025-04-28T10:53:18.619+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2025-04-28T10:53:18.620+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)
[2025-04-28T10:53:18.622+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)
[2025-04-28T10:53:18.630+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:438)
[2025-04-28T10:53:18.631+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-04-28T10:53:18.632+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:272)
[2025-04-28T10:53:18.634+0000] {subprocess.py:93} INFO - 25/04/28 10:53:18 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:18.637+0000] {subprocess.py:93} INFO - 25/04/28 10:53:18 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:18.675+0000] {subprocess.py:93} INFO - 25/04/28 10:53:18 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:18.715+0000] {subprocess.py:93} INFO - 25/04/28 10:53:18 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:18.793+0000] {subprocess.py:93} INFO - 25/04/28 10:53:18 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:18.818+0000] {subprocess.py:93} INFO - 25/04/28 10:53:18 WARN CheckpointFileManager: Failed to rename temp file s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/21/.9.delta.d6c3a036-0d7c-4ac3-893f-bb67184e2e66.TID24.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/21/9.delta because file exists
[2025-04-28T10:53:18.820+0000] {subprocess.py:93} INFO - org.apache.hadoop.fs.FileAlreadyExistsException: Failed to rename s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/21/.9.delta.d6c3a036-0d7c-4ac3-893f-bb67184e2e66.TID24.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/21/9.delta; destination file exists
[2025-04-28T10:53:18.822+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.initiateRename(S3AFileSystem.java:1920)
[2025-04-28T10:53:18.832+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerRename(S3AFileSystem.java:1988)
[2025-04-28T10:53:18.839+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$rename$7(S3AFileSystem.java:1846)
[2025-04-28T10:53:18.843+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-04-28T10:53:18.849+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDuration(IOStatisticsBinding.java:444)
[2025-04-28T10:53:18.852+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2337)
[2025-04-28T10:53:18.863+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.rename(S3AFileSystem.java:1844)
[2025-04-28T10:53:18.864+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.rename(FileSystem.java:1624)
[2025-04-28T10:53:18.865+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.DelegateToFileSystem.renameInternal(DelegateToFileSystem.java:206)
[2025-04-28T10:53:18.866+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.renameInternal(AbstractFileSystem.java:790)
[2025-04-28T10:53:18.866+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[2025-04-28T10:53:18.868+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileContext.rename(FileContext.java:1036)
[2025-04-28T10:53:18.869+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileContextBasedCheckpointFileManager.renameTempFile(CheckpointFileManager.scala:346)
[2025-04-28T10:53:18.869+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.CheckpointFileManager$RenameBasedFSDataOutputStream.close(CheckpointFileManager.scala:154)
[2025-04-28T10:53:18.883+0000] {subprocess.py:93} INFO - 	at net.jpountz.lz4.LZ4BlockOutputStream.close(LZ4BlockOutputStream.java:198)
[2025-04-28T10:53:18.884+0000] {subprocess.py:93} INFO - 	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[2025-04-28T10:53:18.885+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.finalizeDeltaFile(HDFSBackedStateStoreProvider.scala:450)
[2025-04-28T10:53:18.892+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$commitUpdates(HDFSBackedStateStoreProvider.scala:320)
[2025-04-28T10:53:18.901+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider$HDFSBackedStateStore.commit(HDFSBackedStateStoreProvider.scala:141)
[2025-04-28T10:53:18.917+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.StreamingAggregationStateManagerBaseImpl.commit(StreamingAggregationStateManager.scala:89)
[2025-04-28T10:53:18.918+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.$anonfun$close$3(statefulOperators.scala:481)
[2025-04-28T10:53:18.919+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-28T10:53:18.920+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:642)
[2025-04-28T10:53:18.921+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs(statefulOperators.scala:142)
[2025-04-28T10:53:18.924+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs$(statefulOperators.scala:142)
[2025-04-28T10:53:18.929+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec.timeTakenMs(statefulOperators.scala:352)
[2025-04-28T10:53:18.940+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.close(statefulOperators.scala:481)
[2025-04-28T10:53:18.942+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.closeIfNeeded(NextIterator.scala:66)
[2025-04-28T10:53:18.967+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:75)
[2025-04-28T10:53:18.969+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.hashAgg_doAggregateWithKeys_0$(Unknown Source)
[2025-04-28T10:53:18.975+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.processNext(Unknown Source)
[2025-04-28T10:53:18.994+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-04-28T10:53:18.996+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
[2025-04-28T10:53:18.998+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:19.002+0000] {subprocess.py:93} INFO - 	at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)
[2025-04-28T10:53:19.006+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:19.017+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:19.018+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)
[2025-04-28T10:53:19.025+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)
[2025-04-28T10:53:19.029+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:19.030+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2025-04-28T10:53:19.040+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2025-04-28T10:53:19.044+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2025-04-28T10:53:19.053+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)
[2025-04-28T10:53:19.054+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)
[2025-04-28T10:53:19.055+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:438)
[2025-04-28T10:53:19.065+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-04-28T10:53:19.068+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:272)
[2025-04-28T10:53:19.071+0000] {subprocess.py:93} INFO - 25/04/28 10:53:18 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:19.078+0000] {subprocess.py:93} INFO - 25/04/28 10:53:19 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:19.141+0000] {subprocess.py:93} INFO - 25/04/28 10:53:19 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:19.234+0000] {subprocess.py:93} INFO - 25/04/28 10:53:19 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:19.314+0000] {subprocess.py:93} INFO - 25/04/28 10:53:19 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:19.344+0000] {subprocess.py:93} INFO - 25/04/28 10:53:19 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:19.439+0000] {subprocess.py:93} INFO - 25/04/28 10:53:19 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:19.536+0000] {subprocess.py:93} INFO - 25/04/28 10:53:19 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:19.692+0000] {subprocess.py:93} INFO - 25/04/28 10:53:19 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:20.256+0000] {subprocess.py:93} INFO - 25/04/28 10:53:20 WARN CheckpointFileManager: Failed to rename temp file s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/24/.9.delta.b0b25d36-a6d6-4bba-b8eb-f07e5f243648.TID27.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/24/9.delta because file exists
[2025-04-28T10:53:20.284+0000] {subprocess.py:93} INFO - org.apache.hadoop.fs.FileAlreadyExistsException: rename destination s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/24/9.delta already exists.
[2025-04-28T10:53:20.286+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.rename(FileSystem.java:1600)
[2025-04-28T10:53:20.287+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.DelegateToFileSystem.renameInternal(DelegateToFileSystem.java:206)
[2025-04-28T10:53:20.287+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.renameInternal(AbstractFileSystem.java:790)
[2025-04-28T10:53:20.288+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[2025-04-28T10:53:20.291+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileContext.rename(FileContext.java:1036)
[2025-04-28T10:53:20.292+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileContextBasedCheckpointFileManager.renameTempFile(CheckpointFileManager.scala:346)
[2025-04-28T10:53:20.295+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.CheckpointFileManager$RenameBasedFSDataOutputStream.close(CheckpointFileManager.scala:154)
[2025-04-28T10:53:20.297+0000] {subprocess.py:93} INFO - 	at net.jpountz.lz4.LZ4BlockOutputStream.close(LZ4BlockOutputStream.java:198)
[2025-04-28T10:53:20.298+0000] {subprocess.py:93} INFO - 	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[2025-04-28T10:53:20.303+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.finalizeDeltaFile(HDFSBackedStateStoreProvider.scala:450)
[2025-04-28T10:53:20.304+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$commitUpdates(HDFSBackedStateStoreProvider.scala:320)
[2025-04-28T10:53:20.304+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider$HDFSBackedStateStore.commit(HDFSBackedStateStoreProvider.scala:141)
[2025-04-28T10:53:20.305+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.StreamingAggregationStateManagerBaseImpl.commit(StreamingAggregationStateManager.scala:89)
[2025-04-28T10:53:20.318+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.$anonfun$close$3(statefulOperators.scala:481)
[2025-04-28T10:53:20.323+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-28T10:53:20.326+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:642)
[2025-04-28T10:53:20.332+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs(statefulOperators.scala:142)
[2025-04-28T10:53:20.333+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs$(statefulOperators.scala:142)
[2025-04-28T10:53:20.337+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec.timeTakenMs(statefulOperators.scala:352)
[2025-04-28T10:53:20.342+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.close(statefulOperators.scala:481)
[2025-04-28T10:53:20.347+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.closeIfNeeded(NextIterator.scala:66)
[2025-04-28T10:53:20.348+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:75)
[2025-04-28T10:53:20.351+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.hashAgg_doAggregateWithKeys_0$(Unknown Source)
[2025-04-28T10:53:20.353+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.processNext(Unknown Source)
[2025-04-28T10:53:20.354+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-04-28T10:53:20.356+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
[2025-04-28T10:53:20.357+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:20.359+0000] {subprocess.py:93} INFO - 	at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)
[2025-04-28T10:53:20.361+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:20.363+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:20.365+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)
[2025-04-28T10:53:20.367+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)
[2025-04-28T10:53:20.370+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:20.371+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2025-04-28T10:53:20.372+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2025-04-28T10:53:20.373+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2025-04-28T10:53:20.375+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)
[2025-04-28T10:53:20.375+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)
[2025-04-28T10:53:20.376+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:438)
[2025-04-28T10:53:20.377+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-04-28T10:53:20.379+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:272)
[2025-04-28T10:53:20.610+0000] {subprocess.py:93} INFO - 25/04/28 10:53:20 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:20.670+0000] {subprocess.py:93} INFO - 25/04/28 10:53:20 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:20.732+0000] {subprocess.py:93} INFO - 25/04/28 10:53:20 WARN CheckpointFileManager: Failed to rename temp file s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/37/.9.delta.105aebb3-8152-4f08-a33d-4e56258f8269.TID40.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/37/9.delta because file exists
[2025-04-28T10:53:20.909+0000] {subprocess.py:93} INFO - org.apache.hadoop.fs.FileAlreadyExistsException: rename destination s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/37/9.delta already exists.
[2025-04-28T10:53:20.914+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.rename(FileSystem.java:1600)
[2025-04-28T10:53:20.920+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.DelegateToFileSystem.renameInternal(DelegateToFileSystem.java:206)
[2025-04-28T10:53:20.924+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.renameInternal(AbstractFileSystem.java:790)
[2025-04-28T10:53:20.929+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[2025-04-28T10:53:20.931+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileContext.rename(FileContext.java:1036)
[2025-04-28T10:53:20.932+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileContextBasedCheckpointFileManager.renameTempFile(CheckpointFileManager.scala:346)
[2025-04-28T10:53:20.933+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.CheckpointFileManager$RenameBasedFSDataOutputStream.close(CheckpointFileManager.scala:154)
[2025-04-28T10:53:20.934+0000] {subprocess.py:93} INFO - 	at net.jpountz.lz4.LZ4BlockOutputStream.close(LZ4BlockOutputStream.java:198)
[2025-04-28T10:53:20.935+0000] {subprocess.py:93} INFO - 	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[2025-04-28T10:53:20.936+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.finalizeDeltaFile(HDFSBackedStateStoreProvider.scala:450)
[2025-04-28T10:53:20.937+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$commitUpdates(HDFSBackedStateStoreProvider.scala:320)
[2025-04-28T10:53:20.939+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider$HDFSBackedStateStore.commit(HDFSBackedStateStoreProvider.scala:141)
[2025-04-28T10:53:20.942+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.StreamingAggregationStateManagerBaseImpl.commit(StreamingAggregationStateManager.scala:89)
[2025-04-28T10:53:20.945+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.$anonfun$close$3(statefulOperators.scala:481)
[2025-04-28T10:53:20.947+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-28T10:53:20.948+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:642)
[2025-04-28T10:53:20.949+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs(statefulOperators.scala:142)
[2025-04-28T10:53:20.951+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs$(statefulOperators.scala:142)
[2025-04-28T10:53:20.953+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec.timeTakenMs(statefulOperators.scala:352)
[2025-04-28T10:53:20.954+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.close(statefulOperators.scala:481)
[2025-04-28T10:53:20.955+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.closeIfNeeded(NextIterator.scala:66)
[2025-04-28T10:53:20.957+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:75)
[2025-04-28T10:53:20.971+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.hashAgg_doAggregateWithKeys_0$(Unknown Source)
[2025-04-28T10:53:20.972+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.processNext(Unknown Source)
[2025-04-28T10:53:20.976+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-04-28T10:53:20.978+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
[2025-04-28T10:53:20.988+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:20.991+0000] {subprocess.py:93} INFO - 	at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)
[2025-04-28T10:53:20.992+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:20.994+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:20.995+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)
[2025-04-28T10:53:20.999+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)
[2025-04-28T10:53:21.000+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:21.001+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2025-04-28T10:53:21.002+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2025-04-28T10:53:21.007+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2025-04-28T10:53:21.020+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)
[2025-04-28T10:53:21.022+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)
[2025-04-28T10:53:21.023+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:438)
[2025-04-28T10:53:21.024+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-04-28T10:53:21.025+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:272)
[2025-04-28T10:53:21.026+0000] {subprocess.py:93} INFO - 25/04/28 10:53:20 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.026+0000] {subprocess.py:93} INFO - 25/04/28 10:53:20 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.028+0000] {subprocess.py:93} INFO - 25/04/28 10:53:20 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.036+0000] {subprocess.py:93} INFO - 25/04/28 10:53:21 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.106+0000] {subprocess.py:93} INFO - 25/04/28 10:53:21 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.141+0000] {subprocess.py:93} INFO - 25/04/28 10:53:21 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.172+0000] {subprocess.py:93} INFO - 25/04/28 10:53:21 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.256+0000] {subprocess.py:93} INFO - 25/04/28 10:53:21 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.313+0000] {subprocess.py:93} INFO - 25/04/28 10:53:21 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.389+0000] {subprocess.py:93} INFO - 25/04/28 10:53:21 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.485+0000] {subprocess.py:93} INFO - 25/04/28 10:53:21 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.524+0000] {subprocess.py:93} INFO - 25/04/28 10:53:21 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.688+0000] {subprocess.py:93} INFO - 25/04/28 10:53:21 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:21.958+0000] {subprocess.py:93} INFO - 25/04/28 10:53:21 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:22.435+0000] {subprocess.py:93} INFO - 25/04/28 10:53:22 WARN CheckpointFileManager: Failed to rename temp file s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/47/.9.delta.d87b3f2d-09e3-443d-85ec-4603e9d17e32.TID50.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/47/9.delta because file exists
[2025-04-28T10:53:22.457+0000] {subprocess.py:93} INFO - org.apache.hadoop.fs.FileAlreadyExistsException: Failed to rename s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/47/.9.delta.d87b3f2d-09e3-443d-85ec-4603e9d17e32.TID50.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/47/9.delta; destination file exists
[2025-04-28T10:53:22.459+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.initiateRename(S3AFileSystem.java:1920)
[2025-04-28T10:53:22.461+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerRename(S3AFileSystem.java:1988)
[2025-04-28T10:53:22.463+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$rename$7(S3AFileSystem.java:1846)
[2025-04-28T10:53:22.465+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-04-28T10:53:22.466+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDuration(IOStatisticsBinding.java:444)
[2025-04-28T10:53:22.468+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2337)
[2025-04-28T10:53:22.469+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.rename(S3AFileSystem.java:1844)
[2025-04-28T10:53:22.471+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.rename(FileSystem.java:1624)
[2025-04-28T10:53:22.502+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.DelegateToFileSystem.renameInternal(DelegateToFileSystem.java:206)
[2025-04-28T10:53:22.512+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.renameInternal(AbstractFileSystem.java:790)
[2025-04-28T10:53:22.514+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[2025-04-28T10:53:22.515+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileContext.rename(FileContext.java:1036)
[2025-04-28T10:53:22.515+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileContextBasedCheckpointFileManager.renameTempFile(CheckpointFileManager.scala:346)
[2025-04-28T10:53:22.517+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.CheckpointFileManager$RenameBasedFSDataOutputStream.close(CheckpointFileManager.scala:154)
[2025-04-28T10:53:22.518+0000] {subprocess.py:93} INFO - 	at net.jpountz.lz4.LZ4BlockOutputStream.close(LZ4BlockOutputStream.java:198)
[2025-04-28T10:53:22.519+0000] {subprocess.py:93} INFO - 	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[2025-04-28T10:53:22.520+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.finalizeDeltaFile(HDFSBackedStateStoreProvider.scala:450)
[2025-04-28T10:53:22.521+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$commitUpdates(HDFSBackedStateStoreProvider.scala:320)
[2025-04-28T10:53:22.522+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider$HDFSBackedStateStore.commit(HDFSBackedStateStoreProvider.scala:141)
[2025-04-28T10:53:22.522+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.StreamingAggregationStateManagerBaseImpl.commit(StreamingAggregationStateManager.scala:89)
[2025-04-28T10:53:22.523+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.$anonfun$close$3(statefulOperators.scala:481)
[2025-04-28T10:53:22.524+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-28T10:53:22.525+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:642)
[2025-04-28T10:53:22.525+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs(statefulOperators.scala:142)
[2025-04-28T10:53:22.526+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs$(statefulOperators.scala:142)
[2025-04-28T10:53:22.527+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec.timeTakenMs(statefulOperators.scala:352)
[2025-04-28T10:53:22.528+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.close(statefulOperators.scala:481)
[2025-04-28T10:53:22.530+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.closeIfNeeded(NextIterator.scala:66)
[2025-04-28T10:53:22.531+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:75)
[2025-04-28T10:53:22.532+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.hashAgg_doAggregateWithKeys_0$(Unknown Source)
[2025-04-28T10:53:22.533+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.processNext(Unknown Source)
[2025-04-28T10:53:22.534+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-04-28T10:53:22.535+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
[2025-04-28T10:53:22.536+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:22.537+0000] {subprocess.py:93} INFO - 	at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)
[2025-04-28T10:53:22.537+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:22.538+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:22.540+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)
[2025-04-28T10:53:22.541+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)
[2025-04-28T10:53:22.541+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:22.542+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2025-04-28T10:53:22.544+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2025-04-28T10:53:22.544+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2025-04-28T10:53:22.545+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)
[2025-04-28T10:53:22.546+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)
[2025-04-28T10:53:22.547+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:438)
[2025-04-28T10:53:22.548+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-04-28T10:53:22.549+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:272)
[2025-04-28T10:53:24.685+0000] {subprocess.py:93} INFO - 25/04/28 10:53:24 WARN CheckpointFileManager: Failed to rename temp file s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/51/.9.delta.79e42216-865d-48ed-b314-fe042f2ceb1a.TID54.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/51/9.delta because file exists
[2025-04-28T10:53:24.720+0000] {subprocess.py:93} INFO - org.apache.hadoop.fs.FileAlreadyExistsException: rename destination s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/51/9.delta already exists.
[2025-04-28T10:53:24.721+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.rename(FileSystem.java:1600)
[2025-04-28T10:53:24.722+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.DelegateToFileSystem.renameInternal(DelegateToFileSystem.java:206)
[2025-04-28T10:53:24.723+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.renameInternal(AbstractFileSystem.java:790)
[2025-04-28T10:53:24.724+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[2025-04-28T10:53:24.725+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileContext.rename(FileContext.java:1036)
[2025-04-28T10:53:24.727+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileContextBasedCheckpointFileManager.renameTempFile(CheckpointFileManager.scala:346)
[2025-04-28T10:53:24.728+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.CheckpointFileManager$RenameBasedFSDataOutputStream.close(CheckpointFileManager.scala:154)
[2025-04-28T10:53:24.730+0000] {subprocess.py:93} INFO - 	at net.jpountz.lz4.LZ4BlockOutputStream.close(LZ4BlockOutputStream.java:198)
[2025-04-28T10:53:24.731+0000] {subprocess.py:93} INFO - 	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[2025-04-28T10:53:24.732+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.finalizeDeltaFile(HDFSBackedStateStoreProvider.scala:450)
[2025-04-28T10:53:24.733+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$commitUpdates(HDFSBackedStateStoreProvider.scala:320)
[2025-04-28T10:53:24.735+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider$HDFSBackedStateStore.commit(HDFSBackedStateStoreProvider.scala:141)
[2025-04-28T10:53:24.736+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.StreamingAggregationStateManagerBaseImpl.commit(StreamingAggregationStateManager.scala:89)
[2025-04-28T10:53:24.737+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.$anonfun$close$3(statefulOperators.scala:481)
[2025-04-28T10:53:24.738+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-28T10:53:24.739+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:642)
[2025-04-28T10:53:24.740+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs(statefulOperators.scala:142)
[2025-04-28T10:53:24.740+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs$(statefulOperators.scala:142)
[2025-04-28T10:53:24.741+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec.timeTakenMs(statefulOperators.scala:352)
[2025-04-28T10:53:24.742+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.close(statefulOperators.scala:481)
[2025-04-28T10:53:24.743+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.closeIfNeeded(NextIterator.scala:66)
[2025-04-28T10:53:24.745+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:75)
[2025-04-28T10:53:24.746+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.hashAgg_doAggregateWithKeys_0$(Unknown Source)
[2025-04-28T10:53:24.746+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.processNext(Unknown Source)
[2025-04-28T10:53:24.747+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-04-28T10:53:24.748+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
[2025-04-28T10:53:24.751+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:24.752+0000] {subprocess.py:93} INFO - 	at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)
[2025-04-28T10:53:24.752+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:24.753+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:24.754+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)
[2025-04-28T10:53:24.754+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)
[2025-04-28T10:53:24.755+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:24.756+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2025-04-28T10:53:24.756+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2025-04-28T10:53:24.757+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2025-04-28T10:53:24.757+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)
[2025-04-28T10:53:24.758+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)
[2025-04-28T10:53:24.759+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:438)
[2025-04-28T10:53:24.760+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-04-28T10:53:24.761+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:272)
[2025-04-28T10:53:24.762+0000] {subprocess.py:93} INFO - 25/04/28 10:53:24 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:24.935+0000] {subprocess.py:93} INFO - 25/04/28 10:53:24 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:25.099+0000] {subprocess.py:93} INFO - 25/04/28 10:53:25 WARN CheckpointFileManager: Failed to rename temp file s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/48/.9.delta.6d6b4890-847b-4b67-85f0-ba215f365115.TID51.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/48/9.delta because file exists
[2025-04-28T10:53:25.143+0000] {subprocess.py:93} INFO - org.apache.hadoop.fs.FileAlreadyExistsException: Failed to rename s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/48/.9.delta.6d6b4890-847b-4b67-85f0-ba215f365115.TID51.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/48/9.delta; destination file exists
[2025-04-28T10:53:25.146+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.initiateRename(S3AFileSystem.java:1920)
[2025-04-28T10:53:25.148+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerRename(S3AFileSystem.java:1988)
[2025-04-28T10:53:25.163+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$rename$7(S3AFileSystem.java:1846)
[2025-04-28T10:53:25.169+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-04-28T10:53:25.171+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDuration(IOStatisticsBinding.java:444)
[2025-04-28T10:53:25.174+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2337)
[2025-04-28T10:53:25.176+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.rename(S3AFileSystem.java:1844)
[2025-04-28T10:53:25.183+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.rename(FileSystem.java:1624)
[2025-04-28T10:53:25.185+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.DelegateToFileSystem.renameInternal(DelegateToFileSystem.java:206)
[2025-04-28T10:53:25.188+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.renameInternal(AbstractFileSystem.java:790)
[2025-04-28T10:53:25.189+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[2025-04-28T10:53:25.191+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileContext.rename(FileContext.java:1036)
[2025-04-28T10:53:25.200+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileContextBasedCheckpointFileManager.renameTempFile(CheckpointFileManager.scala:346)
[2025-04-28T10:53:25.202+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.CheckpointFileManager$RenameBasedFSDataOutputStream.close(CheckpointFileManager.scala:154)
[2025-04-28T10:53:25.203+0000] {subprocess.py:93} INFO - 	at net.jpountz.lz4.LZ4BlockOutputStream.close(LZ4BlockOutputStream.java:198)
[2025-04-28T10:53:25.207+0000] {subprocess.py:93} INFO - 	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[2025-04-28T10:53:25.210+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.finalizeDeltaFile(HDFSBackedStateStoreProvider.scala:450)
[2025-04-28T10:53:25.213+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$commitUpdates(HDFSBackedStateStoreProvider.scala:320)
[2025-04-28T10:53:25.220+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider$HDFSBackedStateStore.commit(HDFSBackedStateStoreProvider.scala:141)
[2025-04-28T10:53:25.232+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.StreamingAggregationStateManagerBaseImpl.commit(StreamingAggregationStateManager.scala:89)
[2025-04-28T10:53:25.251+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.$anonfun$close$3(statefulOperators.scala:481)
[2025-04-28T10:53:25.255+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-28T10:53:25.266+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:642)
[2025-04-28T10:53:25.297+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs(statefulOperators.scala:142)
[2025-04-28T10:53:25.308+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs$(statefulOperators.scala:142)
[2025-04-28T10:53:25.309+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec.timeTakenMs(statefulOperators.scala:352)
[2025-04-28T10:53:25.312+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.close(statefulOperators.scala:481)
[2025-04-28T10:53:25.314+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.closeIfNeeded(NextIterator.scala:66)
[2025-04-28T10:53:25.325+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:75)
[2025-04-28T10:53:25.328+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.hashAgg_doAggregateWithKeys_0$(Unknown Source)
[2025-04-28T10:53:25.331+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.processNext(Unknown Source)
[2025-04-28T10:53:25.335+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-04-28T10:53:25.357+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
[2025-04-28T10:53:25.359+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:25.361+0000] {subprocess.py:93} INFO - 	at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)
[2025-04-28T10:53:25.369+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:25.371+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:25.372+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)
[2025-04-28T10:53:25.374+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)
[2025-04-28T10:53:25.374+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:25.376+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2025-04-28T10:53:25.377+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2025-04-28T10:53:25.379+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2025-04-28T10:53:25.383+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)
[2025-04-28T10:53:25.385+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)
[2025-04-28T10:53:25.386+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:438)
[2025-04-28T10:53:25.387+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-04-28T10:53:25.389+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:272)
[2025-04-28T10:53:25.391+0000] {subprocess.py:93} INFO - 25/04/28 10:53:25 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:25.405+0000] {subprocess.py:93} INFO - 25/04/28 10:53:25 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:25.606+0000] {subprocess.py:93} INFO - 25/04/28 10:53:25 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:25.808+0000] {subprocess.py:93} INFO - 25/04/28 10:53:25 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:25.902+0000] {subprocess.py:93} INFO - 25/04/28 10:53:25 WARN CheckpointFileManager: Failed to rename temp file s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/56/.9.delta.392879f3-fd39-4867-b004-a25d08483e21.TID59.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/56/9.delta because file exists
[2025-04-28T10:53:25.915+0000] {subprocess.py:93} INFO - org.apache.hadoop.fs.FileAlreadyExistsException: rename destination s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/56/9.delta already exists.
[2025-04-28T10:53:25.916+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.rename(FileSystem.java:1600)
[2025-04-28T10:53:25.917+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.DelegateToFileSystem.renameInternal(DelegateToFileSystem.java:206)
[2025-04-28T10:53:25.918+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.renameInternal(AbstractFileSystem.java:790)
[2025-04-28T10:53:25.918+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[2025-04-28T10:53:25.919+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileContext.rename(FileContext.java:1036)
[2025-04-28T10:53:25.920+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileContextBasedCheckpointFileManager.renameTempFile(CheckpointFileManager.scala:346)
[2025-04-28T10:53:25.921+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.CheckpointFileManager$RenameBasedFSDataOutputStream.close(CheckpointFileManager.scala:154)
[2025-04-28T10:53:25.923+0000] {subprocess.py:93} INFO - 	at net.jpountz.lz4.LZ4BlockOutputStream.close(LZ4BlockOutputStream.java:198)
[2025-04-28T10:53:25.924+0000] {subprocess.py:93} INFO - 	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[2025-04-28T10:53:25.925+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.finalizeDeltaFile(HDFSBackedStateStoreProvider.scala:450)
[2025-04-28T10:53:25.926+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$commitUpdates(HDFSBackedStateStoreProvider.scala:320)
[2025-04-28T10:53:25.927+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider$HDFSBackedStateStore.commit(HDFSBackedStateStoreProvider.scala:141)
[2025-04-28T10:53:25.929+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.StreamingAggregationStateManagerBaseImpl.commit(StreamingAggregationStateManager.scala:89)
[2025-04-28T10:53:25.930+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.$anonfun$close$3(statefulOperators.scala:481)
[2025-04-28T10:53:25.932+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-28T10:53:25.934+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:642)
[2025-04-28T10:53:25.935+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs(statefulOperators.scala:142)
[2025-04-28T10:53:25.937+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs$(statefulOperators.scala:142)
[2025-04-28T10:53:25.938+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec.timeTakenMs(statefulOperators.scala:352)
[2025-04-28T10:53:25.939+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.close(statefulOperators.scala:481)
[2025-04-28T10:53:25.941+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.closeIfNeeded(NextIterator.scala:66)
[2025-04-28T10:53:25.943+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:75)
[2025-04-28T10:53:25.945+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.hashAgg_doAggregateWithKeys_0$(Unknown Source)
[2025-04-28T10:53:25.946+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.processNext(Unknown Source)
[2025-04-28T10:53:25.947+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-04-28T10:53:25.949+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
[2025-04-28T10:53:25.950+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:25.952+0000] {subprocess.py:93} INFO - 	at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)
[2025-04-28T10:53:25.954+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:25.958+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:25.961+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)
[2025-04-28T10:53:25.963+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)
[2025-04-28T10:53:25.965+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:25.966+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2025-04-28T10:53:25.967+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2025-04-28T10:53:25.968+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2025-04-28T10:53:25.969+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)
[2025-04-28T10:53:25.970+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)
[2025-04-28T10:53:25.971+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:438)
[2025-04-28T10:53:25.973+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-04-28T10:53:25.974+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:272)
[2025-04-28T10:53:25.975+0000] {subprocess.py:93} INFO - 25/04/28 10:53:25 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:26.001+0000] {subprocess.py:93} INFO - 25/04/28 10:53:26 WARN CheckpointFileManager: Failed to rename temp file s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/54/.9.delta.ea2b6ebf-a0ea-4574-8a64-452398a8677e.TID57.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/54/9.delta because file exists
[2025-04-28T10:53:26.003+0000] {subprocess.py:93} INFO - org.apache.hadoop.fs.FileAlreadyExistsException: Failed to rename s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/54/.9.delta.ea2b6ebf-a0ea-4574-8a64-452398a8677e.TID57.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/54/9.delta; destination file exists
[2025-04-28T10:53:26.004+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.initiateRename(S3AFileSystem.java:1920)
[2025-04-28T10:53:26.006+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerRename(S3AFileSystem.java:1988)
[2025-04-28T10:53:26.007+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$rename$7(S3AFileSystem.java:1846)
[2025-04-28T10:53:26.008+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-04-28T10:53:26.009+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDuration(IOStatisticsBinding.java:444)
[2025-04-28T10:53:26.010+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2337)
[2025-04-28T10:53:26.011+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.rename(S3AFileSystem.java:1844)
[2025-04-28T10:53:26.013+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.rename(FileSystem.java:1624)
[2025-04-28T10:53:26.014+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.DelegateToFileSystem.renameInternal(DelegateToFileSystem.java:206)
[2025-04-28T10:53:26.015+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.renameInternal(AbstractFileSystem.java:790)
[2025-04-28T10:53:26.017+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[2025-04-28T10:53:26.019+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileContext.rename(FileContext.java:1036)
[2025-04-28T10:53:26.020+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileContextBasedCheckpointFileManager.renameTempFile(CheckpointFileManager.scala:346)
[2025-04-28T10:53:26.021+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.CheckpointFileManager$RenameBasedFSDataOutputStream.close(CheckpointFileManager.scala:154)
[2025-04-28T10:53:26.022+0000] {subprocess.py:93} INFO - 	at net.jpountz.lz4.LZ4BlockOutputStream.close(LZ4BlockOutputStream.java:198)
[2025-04-28T10:53:26.023+0000] {subprocess.py:93} INFO - 	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[2025-04-28T10:53:26.025+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.finalizeDeltaFile(HDFSBackedStateStoreProvider.scala:450)
[2025-04-28T10:53:26.026+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$commitUpdates(HDFSBackedStateStoreProvider.scala:320)
[2025-04-28T10:53:26.027+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider$HDFSBackedStateStore.commit(HDFSBackedStateStoreProvider.scala:141)
[2025-04-28T10:53:26.028+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.StreamingAggregationStateManagerBaseImpl.commit(StreamingAggregationStateManager.scala:89)
[2025-04-28T10:53:26.029+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.$anonfun$close$3(statefulOperators.scala:481)
[2025-04-28T10:53:26.030+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-28T10:53:26.030+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:642)
[2025-04-28T10:53:26.031+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs(statefulOperators.scala:142)
[2025-04-28T10:53:26.033+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs$(statefulOperators.scala:142)
[2025-04-28T10:53:26.035+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec.timeTakenMs(statefulOperators.scala:352)
[2025-04-28T10:53:26.037+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.close(statefulOperators.scala:481)
[2025-04-28T10:53:26.040+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.closeIfNeeded(NextIterator.scala:66)
[2025-04-28T10:53:26.042+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:75)
[2025-04-28T10:53:26.045+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.hashAgg_doAggregateWithKeys_0$(Unknown Source)
[2025-04-28T10:53:26.047+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.processNext(Unknown Source)
[2025-04-28T10:53:26.048+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-04-28T10:53:26.049+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
[2025-04-28T10:53:26.050+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:26.051+0000] {subprocess.py:93} INFO - 	at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)
[2025-04-28T10:53:26.052+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:26.054+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:26.055+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)
[2025-04-28T10:53:26.058+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)
[2025-04-28T10:53:26.076+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:53:26.077+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2025-04-28T10:53:26.079+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2025-04-28T10:53:26.080+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2025-04-28T10:53:26.081+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)
[2025-04-28T10:53:26.083+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)
[2025-04-28T10:53:26.087+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:438)
[2025-04-28T10:53:26.089+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-04-28T10:53:26.099+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:272)
[2025-04-28T10:53:26.103+0000] {subprocess.py:93} INFO - 25/04/28 10:53:26 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:26.157+0000] {subprocess.py:93} INFO - 25/04/28 10:53:26 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:26.204+0000] {subprocess.py:93} INFO - 25/04/28 10:53:26 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:26.266+0000] {subprocess.py:93} INFO - 25/04/28 10:53:26 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:26.348+0000] {subprocess.py:93} INFO - 25/04/28 10:53:26 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:26.426+0000] {subprocess.py:93} INFO - 25/04/28 10:53:26 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:26.513+0000] {subprocess.py:93} INFO - 25/04/28 10:53:26 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:26.574+0000] {subprocess.py:93} INFO - 25/04/28 10:53:26 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:26.618+0000] {subprocess.py:93} INFO - 25/04/28 10:53:26 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:26.673+0000] {subprocess.py:93} INFO - 25/04/28 10:53:26 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:26.734+0000] {subprocess.py:93} INFO - 25/04/28 10:53:26 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:27.024+0000] {subprocess.py:93} INFO - 25/04/28 10:53:27 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:27.284+0000] {subprocess.py:93} INFO - 25/04/28 10:53:27 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:27.763+0000] {subprocess.py:93} INFO - 25/04/28 10:53:27 WARN HDFSBackedStateStoreProvider: The state for version 8 doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.
[2025-04-28T10:53:30.721+0000] {job.py:213} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/job.py", line 308, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-28T10:53:31.454+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-04-28T10:53:48.183+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-04-28T10:54:06.024+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-04-28T10:54:26.387+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-04-28T10:54:28.831+0000] {subprocess.py:93} INFO - 25/04/28 10:54:28 WARN CheckpointFileManager: Failed to rename temp file s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/66/.9.delta.f3430789-a688-438e-92fa-f92e4376d0b3.TID69.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/66/9.delta because file exists
[2025-04-28T10:54:29.023+0000] {subprocess.py:93} INFO - org.apache.hadoop.fs.FileAlreadyExistsException: Failed to rename s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/66/.9.delta.f3430789-a688-438e-92fa-f92e4376d0b3.TID69.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/66/9.delta; destination file exists
[2025-04-28T10:54:29.181+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.initiateRename(S3AFileSystem.java:1920)
[2025-04-28T10:54:29.335+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerRename(S3AFileSystem.java:1988)
[2025-04-28T10:54:29.409+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$rename$7(S3AFileSystem.java:1846)
[2025-04-28T10:54:29.420+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-04-28T10:54:29.421+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDuration(IOStatisticsBinding.java:444)
[2025-04-28T10:54:29.422+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2337)
[2025-04-28T10:54:29.422+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.rename(S3AFileSystem.java:1844)
[2025-04-28T10:54:29.423+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.rename(FileSystem.java:1624)
[2025-04-28T10:54:29.424+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.DelegateToFileSystem.renameInternal(DelegateToFileSystem.java:206)
[2025-04-28T10:54:29.425+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.renameInternal(AbstractFileSystem.java:790)
[2025-04-28T10:54:29.425+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[2025-04-28T10:54:29.426+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileContext.rename(FileContext.java:1036)
[2025-04-28T10:54:29.427+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileContextBasedCheckpointFileManager.renameTempFile(CheckpointFileManager.scala:346)
[2025-04-28T10:54:29.427+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.CheckpointFileManager$RenameBasedFSDataOutputStream.close(CheckpointFileManager.scala:154)
[2025-04-28T10:54:29.428+0000] {subprocess.py:93} INFO - 	at net.jpountz.lz4.LZ4BlockOutputStream.close(LZ4BlockOutputStream.java:198)
[2025-04-28T10:54:29.453+0000] {subprocess.py:93} INFO - 	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[2025-04-28T10:54:29.456+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.finalizeDeltaFile(HDFSBackedStateStoreProvider.scala:450)
[2025-04-28T10:54:29.456+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$commitUpdates(HDFSBackedStateStoreProvider.scala:320)
[2025-04-28T10:54:29.458+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider$HDFSBackedStateStore.commit(HDFSBackedStateStoreProvider.scala:141)
[2025-04-28T10:54:29.459+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.StreamingAggregationStateManagerBaseImpl.commit(StreamingAggregationStateManager.scala:89)
[2025-04-28T10:54:29.460+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.$anonfun$close$3(statefulOperators.scala:481)
[2025-04-28T10:54:29.461+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-28T10:54:29.463+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:642)
[2025-04-28T10:54:29.464+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs(statefulOperators.scala:142)
[2025-04-28T10:54:29.465+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs$(statefulOperators.scala:142)
[2025-04-28T10:54:29.466+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec.timeTakenMs(statefulOperators.scala:352)
[2025-04-28T10:54:29.467+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.close(statefulOperators.scala:481)
[2025-04-28T10:54:29.467+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.closeIfNeeded(NextIterator.scala:66)
[2025-04-28T10:54:29.468+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:75)
[2025-04-28T10:54:29.469+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.hashAgg_doAggregateWithKeys_0$(Unknown Source)
[2025-04-28T10:54:29.469+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.processNext(Unknown Source)
[2025-04-28T10:54:29.470+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-04-28T10:54:29.471+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
[2025-04-28T10:54:29.472+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:54:29.473+0000] {subprocess.py:93} INFO - 	at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)
[2025-04-28T10:54:29.474+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:54:29.475+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:54:29.476+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)
[2025-04-28T10:54:29.477+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)
[2025-04-28T10:54:29.478+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:54:29.478+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2025-04-28T10:54:29.479+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2025-04-28T10:54:29.480+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2025-04-28T10:54:29.480+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)
[2025-04-28T10:54:29.481+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)
[2025-04-28T10:54:29.481+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:438)
[2025-04-28T10:54:29.482+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-04-28T10:54:29.483+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:272)
[2025-04-28T10:54:29.484+0000] {subprocess.py:93} INFO - 25/04/28 10:54:28 WARN CheckpointFileManager: Failed to rename temp file s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/65/.9.delta.b9860d7d-a15c-4ac2-a4bf-4de608bf9dc6.TID68.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/65/9.delta because file exists
[2025-04-28T10:54:29.504+0000] {subprocess.py:93} INFO - org.apache.hadoop.fs.FileAlreadyExistsException: Failed to rename s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/65/.9.delta.b9860d7d-a15c-4ac2-a4bf-4de608bf9dc6.TID68.tmp to s3a://traffic-data/checkpoints_***/traffic_processing_pipeline/traffic_processing_pipeline_debug2/state/0/65/9.delta; destination file exists
[2025-04-28T10:54:29.506+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.initiateRename(S3AFileSystem.java:1920)
[2025-04-28T10:54:29.507+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerRename(S3AFileSystem.java:1988)
[2025-04-28T10:54:29.509+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$rename$7(S3AFileSystem.java:1846)
[2025-04-28T10:54:29.511+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
[2025-04-28T10:54:29.512+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDuration(IOStatisticsBinding.java:444)
[2025-04-28T10:54:29.513+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2337)
[2025-04-28T10:54:29.514+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.s3a.S3AFileSystem.rename(S3AFileSystem.java:1844)
[2025-04-28T10:54:29.515+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.rename(FileSystem.java:1624)
[2025-04-28T10:54:29.516+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.DelegateToFileSystem.renameInternal(DelegateToFileSystem.java:206)
[2025-04-28T10:54:29.516+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.renameInternal(AbstractFileSystem.java:790)
[2025-04-28T10:54:29.517+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[2025-04-28T10:54:29.526+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileContext.rename(FileContext.java:1036)
[2025-04-28T10:54:29.527+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileContextBasedCheckpointFileManager.renameTempFile(CheckpointFileManager.scala:346)
[2025-04-28T10:54:29.527+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.CheckpointFileManager$RenameBasedFSDataOutputStream.close(CheckpointFileManager.scala:154)
[2025-04-28T10:54:29.528+0000] {subprocess.py:93} INFO - 	at net.jpountz.lz4.LZ4BlockOutputStream.close(LZ4BlockOutputStream.java:198)
[2025-04-28T10:54:29.529+0000] {subprocess.py:93} INFO - 	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
[2025-04-28T10:54:29.530+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.finalizeDeltaFile(HDFSBackedStateStoreProvider.scala:450)
[2025-04-28T10:54:29.531+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$commitUpdates(HDFSBackedStateStoreProvider.scala:320)
[2025-04-28T10:54:29.531+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider$HDFSBackedStateStore.commit(HDFSBackedStateStoreProvider.scala:141)
[2025-04-28T10:54:29.532+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.state.StreamingAggregationStateManagerBaseImpl.commit(StreamingAggregationStateManager.scala:89)
[2025-04-28T10:54:29.532+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.$anonfun$close$3(statefulOperators.scala:481)
[2025-04-28T10:54:29.555+0000] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-04-28T10:54:29.556+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.timeTakenMs(Utils.scala:642)
[2025-04-28T10:54:29.557+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs(statefulOperators.scala:142)
[2025-04-28T10:54:29.558+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreWriter.timeTakenMs$(statefulOperators.scala:142)
[2025-04-28T10:54:29.559+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec.timeTakenMs(statefulOperators.scala:352)
[2025-04-28T10:54:29.560+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.StateStoreSaveExec$$anon$2.close(statefulOperators.scala:481)
[2025-04-28T10:54:29.560+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.closeIfNeeded(NextIterator.scala:66)
[2025-04-28T10:54:29.561+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:75)
[2025-04-28T10:54:29.562+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.hashAgg_doAggregateWithKeys_0$(Unknown Source)
[2025-04-28T10:54:29.562+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage7.processNext(Unknown Source)
[2025-04-28T10:54:29.563+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-04-28T10:54:29.564+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
[2025-04-28T10:54:29.565+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:54:29.566+0000] {subprocess.py:93} INFO - 	at org.apache.spark.ContextAwareIterator.hasNext(ContextAwareIterator.scala:39)
[2025-04-28T10:54:29.566+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:54:29.567+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:54:29.568+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1211)
[2025-04-28T10:54:29.568+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1217)
[2025-04-28T10:54:29.569+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-04-28T10:54:29.569+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[2025-04-28T10:54:29.570+0000] {subprocess.py:93} INFO - 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[2025-04-28T10:54:29.571+0000] {subprocess.py:93} INFO - 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[2025-04-28T10:54:29.572+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:307)
[2025-04-28T10:54:29.572+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.writeIteratorToStream(PythonUDFRunner.scala:53)
[2025-04-28T10:54:29.573+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:438)
[2025-04-28T10:54:29.585+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:2066)
[2025-04-28T10:54:29.587+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:272)
[2025-04-28T10:54:42.597+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-04-28T10:54:58.699+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-04-28T10:55:16.686+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-04-28T10:55:38.032+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
